if(sessionStorage.getItem('rco_admin_session')!=='active'){location.replace('login.html');}
(() => {
if(window.RCO_I18N)RCO_I18N.init();
const DEMO=[
{id:'RCO-MT-10004',divisionName:'Mantenimiento',created:new Date().toISOString(),cliente:'CL-10025',propiedad:'PG-0048',nombre:'Rodrigo Orellano',servicio:'Plomería',fecha:new Date().toISOString().slice(0,10),turno:'Mañana',prioridad:'Urgente',estado:'Recibida',tecnico:''},
{id:'RCO-LP-10003',divisionName:'Limpieza',created:new Date(Date.now()-3600000).toISOString(),cliente:'CL-10025',propiedad:'PG-0061',nombre:'Rodrigo Orellano',servicio:'Limpieza',fecha:new Date(Date.now()+86400000).toISOString().slice(0,10),turno:'Tarde',prioridad:'Programado',estado:'Confirmada',tecnico:'Ana · TEC-0034'},
{id:'RCO-IN-10002',divisionName:'Inspecciones',created:new Date(Date.now()-7200000).toISOString(),cliente:'',propiedad:'',nombre:'Pousada Mar Azul',servicio:'Inspección técnica',fecha:new Date().toISOString().slice(0,10),turno:'Tarde',prioridad:'Prioritario',estado:'Técnico asignado',tecnico:'Marcos · TEC-0028'}];
const ACT=[{time:'09:15',text:'Nueva solicitud urgente en PG-0048.',meta:'RCO-MT-10004'},{time:'09:22',text:'Ana fue asignada a la limpieza de PG-0061.',meta:'RCO-LP-10003'},{time:'09:41',text:'Cliente confirmó la visita de la tarde.',meta:'RCO-IN-10002'},{time:'10:05',text:'Sitio web y recepción digital operativos.',meta:'Sistema'}];
let currentId=null,currentFilter='Todas';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function requests(){const a=JSON.parse(localStorage.getItem('rco_requests')||'[]'),m=JSON.parse(localStorage.getItem('rco_managed_requests')||'[]'),map=new Map();[...DEMO,...a,...m].forEach(x=>map.set(x.id,{...x}));return[...map.values()].sort((x,y)=>new Date(y.created||0)-new Date(x.created||0))}
function activities(){return JSON.parse(localStorage.getItem('rco_activity')||JSON.stringify(ACT))}
function pushActivity(text,meta){const n=new Date(),item={time:n.toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}),text,meta};localStorage.setItem('rco_activity',JSON.stringify([item,...activities()].slice(0,30)))}
function dateText(v){const t=new Date().toISOString().slice(0,10),m=new Date(Date.now()+86400000).toISOString().slice(0,10);return v===t?'Hoy':v===m?'Mañana':v?v.split('-').reverse().join('/'):'Sin fecha'}
const active=r=>r.estado!=='Finalizada';
function row(r){return`<div class="request-row ${r.prioridad==='Urgente'?'urgent-row':''}"><div class="request-meta"><small>${esc(r.divisionName||'Servicio')}</small><strong>${esc(r.id)}</strong></div><div class="request-cell"><small>Servicio</small>${esc(r.servicio||'—')}</div><div class="request-cell"><small>Propiedad / cliente</small>${esc(r.propiedad||r.nombre||'Ocasional')}</div><div class="request-cell"><small>Agenda</small>${esc(dateText(r.fecha))} · ${esc(r.turno||'—')}</div><div class="request-actions"><span class="badge ${r.prioridad==='Urgente'?'urgent':''}">${esc(r.prioridad||'Programado')}</span><button class="icon-btn" data-open="${esc(r.id)}">Abrir</button></div></div>`}
function renderAct(id,limit){document.getElementById(id).innerHTML=activities().slice(0,limit||99).map(a=>`<div class="activity-item"><time>${esc(a.time)}</time><div><p>${esc(a.text)}</p><small>${esc(a.meta)}</small></div></div>`).join('')}
function renderAgenda(id,compact){const rs=requests().filter(active),days=[{k:new Date().toISOString().slice(0,10),l:'Hoy'},{k:new Date(Date.now()+86400000).toISOString().slice(0,10),l:'Mañana'},{k:new Date(Date.now()+2*86400000).toISOString().slice(0,10),l:'Próximos'}];document.getElementById(id).innerHTML=days.map((d,i)=>{const items=rs.filter(r=>i<2?r.fecha===d.k:r.fecha>d.k).slice(0,compact?2:10);return`<div class="day-column"><h3>${d.l}</h3>${items.length?items.map(r=>`<div class="agenda-item ${r.prioridad==='Urgente'?'urgent-agenda':''}"><strong>${esc(r.turno||'Turno')}</strong> · ${esc(r.servicio)}<br><small>${esc(r.propiedad||r.nombre||r.id)} · ${esc(r.estado)}</small></div>`).join(''):'<div class="empty-state">Sin servicios</div>'}</div>`}).join('')}
function render(){const list=requests(),open=list.filter(active),urgent=open.filter(r=>r.prioridad==='Urgente'),done=list.filter(r=>r.estado==='Finalizada');kpiOpen.textContent=open.length;kpiUrgent.textContent=urgent.length;kpiDone.textContent=done.length;dailySummary.textContent=`Hoy hay ${open.length} solicitudes activas. ${urgent.length?urgent.length+' requieren atención urgente.':'No hay urgencias pendientes.'}`;priorityList.innerHTML=[...urgent,...open.filter(r=>r.prioridad!=='Urgente')].slice(0,5).map(row).join('')||'<div class="empty-state">No hay solicitudes activas.</div>';const f=list.filter(r=>currentFilter==='Todas'||currentFilter==='Urgente'&&r.prioridad==='Urgente'||r.estado===currentFilter);allRequests.innerHTML=f.map(row).join('')||'<div class="empty-state">No hay solicitudes en este filtro.</div>';renderAct('recentActivity',4);renderAct('fullActivity',30);renderAgenda('miniAgenda',true);renderAgenda('fullAgenda',false);lastSync.textContent='Actualizado '+new Date().toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.open))}
function openDrawer(id){const r=requests().find(x=>x.id===id);if(!r)return;currentId=id;drawerId.textContent=r.id;drawerDetails.innerHTML=`<div class="detail"><small>División</small><strong>${esc(r.divisionName)}</strong></div><div class="detail"><small>Prioridad</small><strong>${esc(r.prioridad)}</strong></div><div class="detail"><small>Cliente</small><strong>${esc(r.cliente||r.nombre||'Ocasional')}</strong></div><div class="detail"><small>Propiedad</small><strong>${esc(r.propiedad||'Sin código')}</strong></div><div class="detail"><small>Fecha y turno</small><strong>${esc(dateText(r.fecha))} · ${esc(r.turno||'—')}</strong></div><div class="detail"><small>Servicio</small><strong>${esc(r.servicio||'—')}</strong></div><div class="detail full"><small>Descripción</small><strong>${esc(r.descripcion||'Sin descripción guardada en esta prueba.')}</strong></div>`;drawerStatus.value=r.estado||'Recibida';drawerTech.value=r.tecnico||'';requestDrawer.hidden=false}
drawerClose.onclick=()=>requestDrawer.hidden=true;requestDrawer.onclick=e=>{if(e.target.id==='requestDrawer')requestDrawer.hidden=true};saveRequest.onclick=()=>{const all=requests(),i=all.findIndex(r=>r.id===currentId);if(i<0)return;const old=all[i].estado;all[i].estado=drawerStatus.value;all[i].tecnico=drawerTech.value;localStorage.setItem('rco_managed_requests',JSON.stringify(all));pushActivity(`${currentId} cambió de “${old}” a “${all[i].estado}”.`,all[i].tecnico||'Sin técnico asignado');requestDrawer.hidden=true;render()};
document.querySelectorAll('.ops-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.ops-nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.ops-section').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.section).classList.add('active')});document.querySelectorAll('[data-open-section]').forEach(b=>b.onclick=()=>document.querySelector(`.ops-nav button[data-section="${b.dataset.openSection}"]`).click());document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()});render()})();