(() => {
const C0=[{id:'CL-10025',name:'Rodrigo Orellano',phone:'+55 81 99899 1468',email:'rodrigo@ejemplo.com',language:'Español',level:'Premium',since:'Julio 2026',notes:'Cliente fundador de demostración.',billing:84300},{id:'CL-10026',name:'Pousada Mar Azul',phone:'+55 81 99988 2211',email:'contato@marazul.com',language:'Português',level:'Corporativo',since:'Julio 2026',notes:'Prioridad en temporada alta.',billing:29400},{id:'CL-10027',name:'Condomínio Solar',phone:'+55 81 98877 5544',email:'adm@solar.com',language:'Português',level:'Administrado',since:'Junio 2026',notes:'Reunión mensual.',billing:51700}];
const P0=[{id:'PG-0048',clientId:'CL-10025',name:'Apartamento Vista Mar',address:'Porto de Galinhas',unit:'Apto. 204',qr:'Activo',last:'18 días',inspection:'15/09/2026',notes:'Llave en recepción.'},{id:'PG-0061',clientId:'CL-10025',name:'Casa Praia',address:'Maracaípe',unit:'Casa 12',qr:'Activo',last:'42 días',inspection:'20/10/2026',notes:'Acceso por portería.'},{id:'RC-0017',clientId:'CL-10025',name:'Local Comercial',address:'Centro',unit:'Loja 03',qr:'Activo',last:'Sin registro',inspection:'01/11/2026',notes:''},{id:'PG-0072',clientId:'CL-10026',name:'Pousada Mar Azul',address:'Rua das Piscinas Naturais',unit:'18 habitaciones',qr:'Activo',last:'3 días',inspection:'05/08/2026',notes:'Contacto: recepción.'}];
const R0=[{id:'TEC-0015',type:'Técnico',name:'Carlos',specialty:'Electricidad',status:'Disponible',rating:'4,9'},{id:'TEC-0021',type:'Técnico',name:'João',specialty:'Hidráulica',status:'En servicio',rating:'4,8'},{id:'TEC-0028',type:'Técnico',name:'Marcos',specialty:'Pintura y reparaciones',status:'Disponible',rating:'4,9'},{id:'TEC-0034',type:'Técnico',name:'Ana',specialty:'Limpieza e inspecciones',status:'Disponible',rating:'5,0'},{id:'VH-0008',type:'Vehículo',name:'Utilitario 01',specialty:'Operativo',status:'Disponible',rating:''},{id:'EQ-0021',type:'Equipo',name:'Kit detección de pérdidas',specialty:'Diagnóstico',status:'En uso',rating:''}];
const load=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),save=(k,d)=>localStorage.setItem(k,JSON.stringify(d)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clients=()=>load('rco_clients',C0),props=()=>load('rco_properties',P0),resources=()=>load('rco_resources',R0),initials=n=>n.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase();
function propertyRow(p){return `<div class="property-row"><div><small>${esc(p.id)}</small><strong>${esc(p.name)}</strong><br><span style="color:var(--muted);font-size:12px">${esc(p.address)} · ${esc(p.unit)}</span></div><div><small>QR</small><strong>${esc(p.qr)}</strong></div><div><small>Próxima inspección</small><strong>${esc(p.inspection)}</strong></div><button class="icon-btn" onclick="alert('${esc(p.id)} · ${esc(p.name)}\\nÚltimo servicio: ${esc(p.last)}\\n${esc(p.notes)}')">Expediente</button></div>`}
function render(filter=''){const cs=clients().filter(c=>(c.name+' '+c.id).toLowerCase().includes(filter.toLowerCase()));clientGrid.innerHTML=cs.map(c=>{const pc=props().filter(p=>p.clientId===c.id).length;return `<article class="crm-card" data-client="${esc(c.id)}"><div class="crm-top"><div class="crm-name"><div class="avatar">${esc(initials(c.name))}</div><div><h3>${esc(c.name)}</h3><p>${esc(c.id)} · ${esc(c.level)}</p></div></div><span class="badge">${esc(c.language)}</span></div><div class="crm-stats"><div class="crm-stat"><strong>${pc}</strong><small>Propiedades</small></div><div class="crm-stat"><strong>${esc(c.level)}</strong><small>Nivel</small></div><div class="crm-stat"><strong>R$ ${(c.billing||0).toLocaleString('pt-BR')}</strong><small>Facturación</small></div></div></article>`}).join('');document.querySelectorAll('[data-client]').forEach(x=>x.onclick=()=>openClient(x.dataset.client));clientsKpi.textContent=clients().length;propertiesKpi.textContent=props().length;qrKpi.textContent=props().filter(p=>p.qr==='Activo').length}
function openClient(id){const c=clients().find(x=>x.id===id),ps=props().filter(p=>p.clientId===id);detailTitle.textContent=c.name;detailContent.innerHTML=`<div class="profile-grid"><aside class="profile-side"><div class="profile-avatar">${esc(initials(c.name))}</div><h2>${esc(c.name)}</h2><p style="color:var(--muted)">${esc(c.id)} · ${esc(c.level)}<br>Cliente desde ${esc(c.since)}</p><p>📱 ${esc(c.phone)}<br>✉ ${esc(c.email||'Sin email')}</p><a class="btn primary" target="_blank" href="https://wa.me/${esc(c.phone.replace(/\\D/g,''))}">WhatsApp</a></aside><section class="profile-main"><div class="record-grid"><div class="record"><small>Propiedades</small><strong>${ps.length}</strong></div><div class="record"><small>Facturación</small><strong>R$ ${(c.billing||0).toLocaleString('pt-BR')}</strong></div><div class="record"><small>Idioma</small><strong>${esc(c.language)}</strong></div><div class="record"><small>Nivel</small><strong>${esc(c.level)}</strong></div></div><h3 style="margin-top:18px">Propiedades asociadas</h3><div class="property-list">${ps.map(propertyRow).join('')||'<div class="empty-state">Sin propiedades</div>'}</div><h3 style="margin-top:18px">Observaciones</h3><div class="record"><strong>${esc(c.notes||'Sin observaciones')}</strong></div></section></div>`;clientDetailModal.hidden=false}
function renderProps(){propertyList.innerHTML=props().map(p=>{const c=clients().find(x=>x.id===p.clientId);return `<div class="property-row"><div><small>${esc(p.id)}</small><strong>${esc(p.name)}</strong><br><span style="color:var(--muted);font-size:12px">${esc(p.address)} · ${esc(p.unit)}</span></div><div><small>Cliente</small><strong>${esc(c?c.name:p.clientId)}</strong></div><div><small>QR / inspección</small><strong>${esc(p.qr)} · ${esc(p.inspection)}</strong></div><button class="icon-btn" onclick="alert('${esc(p.id)} · ${esc(p.name)}\\nÚltimo servicio: ${esc(p.last)}\\n${esc(p.notes)}')">Abrir</button></div>`}).join('')}
function renderResources(){resourceGrid.innerHTML=resources().map(r=>`<article class="resource-card"><small>${esc(r.id)} · ${esc(r.type)}</small><h3>${esc(r.name)}</h3><p style="color:var(--muted)">${esc(r.specialty)}</p><p><span class="status-dot ${r.status.includes('servicio')||r.status.includes('uso')?'busy':''}"></span>${esc(r.status)} ${r.rating?'· ★ '+esc(r.rating):''}</p></article>`).join('')}
function fillClients(){propertyClientSelect.innerHTML=clients().map(c=>`<option value="${esc(c.id)}">${esc(c.id)} · ${esc(c.name)}</option>`).join('')}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.core-section').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).hidden=true);document.querySelectorAll('.core-modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.hidden=true});
clientSearch.oninput=e=>render(e.target.value);newClientBtn.onclick=()=>newClientModal.hidden=false;newPropertyBtn.onclick=()=>{fillClients();newPropertyModal.hidden=false};
newClientForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),a=clients(),id='CL-'+String(10025+a.length).padStart(5,'0');a.push({id,name:f.get('name'),phone:f.get('phone'),email:f.get('email'),language:f.get('language'),level:'Nuevo',since:new Date().toLocaleDateString('es-AR',{month:'long',year:'numeric'}),notes:f.get('notes'),billing:0});save('rco_clients',a);e.target.reset();newClientModal.hidden=true;render();fillClients()};
newPropertyForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),a=props(),id='PG-'+String(48+a.length+1).padStart(4,'0');a.push({id,clientId:f.get('clientId'),name:f.get('name'),address:f.get('address'),unit:f.get('unit'),qr:'Pendiente',last:'Sin registro',inspection:'Sin programar',notes:f.get('notes')});save('rco_properties',a);e.target.reset();newPropertyModal.hidden=true;render();renderProps()};
render();renderProps();renderResources();fillClients();
})();